#!/usr/bin/php
<?php

// We do need access to Composer libs
require_once realpath( __DIR__ . '/../' ) . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use P24\Console\Command\ScreencaptureCommand;

$application = new Application();
$application->add(new ScreencaptureCommand());
$application->run();
